from __future__ import annotations
import json,subprocess
from datetime import datetime,timedelta,timezone
from pathlib import Path
from typing import Any
from across_edge_worker.models import WORKER_PROTOCOL_VERSION,sha256_json
def make_repo(root:Path,files:dict[str,str]|None=None):
 root.mkdir(parents=True,exist_ok=True);subprocess.run(["git","init","-q",str(root)],check=True);subprocess.run(["git","-C",str(root),"config","user.name","fixture"],check=True);subprocess.run(["git","-C",str(root),"config","user.email","fixture@example.invalid"],check=True)
 for name,content in (files or {"client.py":"def retain(events):\n    return events\n"}).items():p=root/name;p.parent.mkdir(parents=True,exist_ok=True);p.write_text(content)
 subprocess.run(["git","-C",str(root),"add","-A"],check=True);subprocess.run(["git","-C",str(root),"commit","-qm","fixture"],check=True);return root,subprocess.check_output(["git","-C",str(root),"rev-parse","HEAD"],text=True).strip()
def job_dict(target,sha,*,job_id="job-1",capabilities=None,actions=None,checks=None,mutation=False):
 caps=capabilities or ["event_log_decoding","sdk_client_repair","unsigned_transaction_validation","relayer_reconciliation","fee_logic_verification"];topic="0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef";acts=[{"capability":"event_log_decoding","log":{"topics":[topic,"0x"+"0"*24+"11"*20,"0x"+"0"*24+"22"*20],"data":"0x"+f"{123:064x}","blockNumber":"0x10","blockHash":"0x"+"33"*32}},{"capability":"sdk_client_repair","repair_id":"bound-retention","path":"client.py","old":"    return events\n","new":"    return events[-128:]\n"},{"capability":"unsigned_transaction_validation","transaction":{"chain_id":42161,"to":"0x"+"44"*20,"data":"0x1234","value":0}},{"capability":"relayer_reconciliation","attempts":[{"deposit_id":"d1","evaluation_id":"e1","observed_at":1,"decision":"UNKNOWN","block_hash":None,"net_fee_wei":None},{"deposit_id":"d1","evaluation_id":"e1","observed_at":2,"decision":"profitable","block_hash":"0xabc","net_fee_wei":5},{"deposit_id":"d2","evaluation_id":"e2","observed_at":3,"decision":"unprofitable","block_hash":"0xdef","net_fee_wei":-1}]},{"capability":"fee_logic_verification","inputs":{"gross_fee_wei":1000,"gas_cost_wei":100,"capital_cost_wei":20,"rebalance_cost_wei":30}}];raw={"schema_version":WORKER_PROTOCOL_VERSION,"job_id":job_id,"canonical_opportunity_id":"opp-1","worker_id":"across-edge","work_lease_id":"lease-1","scope_hash":"","frozen_acceptance_criteria":{"must_return":"WorkerResult","authority":"read-only"},"target_repository":str(target),"target_base_sha":sha,"allowed_paths":["client.py"],"required_capabilities":caps,"structured_requirements":{"actions":acts if actions is None else actions,"requested_chain_ids":[42161],"requested_read_endpoints":[],"external_protocol_mutation":mutation},"expected_deliverable":{"kind":"patch+analysis"},"deterministic_checks":checks or [{"kind":"file_contains","path":"client.py","needle":"return events[-128:]"}],"allowed_chain_ids":[42161,8453],"allowed_read_endpoints":[],"max_spend_usd":0,"lease_status":"ACTIVE","lease_expires_at":(datetime.now(timezone.utc)+timedelta(hours=1)).isoformat().replace("+00:00","Z"),"timeout_seconds":60};m=dict(raw);m.pop("scope_hash");raw["scope_hash"]=sha256_json(m);return raw
def write_job(path,raw):path.write_text(json.dumps(raw,indent=2,sort_keys=True)+"\n")
