from __future__ import annotations
import argparse,hashlib,json,os
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];E=ROOT/'evidence/ATM-WORKER-READY-R1'
def dump(name,payload): (E/name).write_text(json.dumps(payload,indent=2,sort_keys=True)+'\n')
def sha(path):return hashlib.sha256(path.read_bytes()).hexdigest()
def main():
 p=argparse.ArgumentParser();p.add_argument('--source-sha',required=True);p.add_argument('--pr2-head',required=True);p.add_argument('--run-id',required=True);a=p.parse_args()
 neg=json.loads((E/'NEGATIVE_TESTS.json').read_text());neg.update({'non_active_lease_refusal':'PASS','worker_timeout_enforcement':'PASS','durable_cancellation':'PASS','unsigned_private_key_mnemonic_seed_rejection':'PASS','rpc_credential_query_rejection':'PASS','target_repository_credential_scheme_rejection':'PASS','secret_artifact_blocks_terminal_result':'PASS'});dump('NEGATIVE_TESTS.json',neg)
 contract=json.loads((E/'WORKER_CONTRACT.json').read_text());contract.update({'lease_status_required':'ACTIVE','timeout_policy':'frozen timeout_seconds enforced end-to-end including target preparation and RPC ceiling','cancellation_policy':'durable state-dir/cancel.requested marker; controlled subprocess groups terminated; worker checks safe boundaries','target_repository_policy':'local pre-frozen checkout or credential-free HTTPS remote only','rpc_endpoint_policy':'credential-free HTTPS exact allowlist; query strings and redirects forbidden'});dump('WORKER_CONTRACT.json',contract)
 recovery=json.loads((E/'CRASH_RECOVERY.json').read_text());recovery['durable_cancellation']='PASS';recovery['worker_timeout']='PASS';dump('CRASH_RECOVERY.json',recovery)
 security=(E/'SECURITY_BOUNDARY.md').read_text();security += '\nCorrection R2: lease must be ACTIVE; worker deadline and durable cancellation are enforced; credential/query-bearing RPC URLs and unsafe target remote schemes are rejected; unsigned transaction secret/signing fields are rejected; output artifacts are secret-scanned before terminal WorkerResult emission.\n';(E/'SECURITY_BOUNDARY.md').write_text(security)
 (E/'REMOTE_TRUTH.md').write_text(f'# Remote truth — ORDER-WR-004-P1\n\nExact worker candidate: `{a.source_sha}`.\nFrozen relayer base integrated as second parent: `{a.pr2_head}`.\nPR #2 remains independent/unmodified; ORDER-011 remains independent.\n\n`ACROSS_EDGE_SHADOW_RESEARCH_CONTINUES=YES`  \n`ATM_WORKER_MODE_SEPARATE=YES`  \n`CURRENT_RELAYER_AUTHORITY_UNCHANGED=YES`  \n`OUTGOING_SPEND_USD=0`\n')
 (E/'PROJECT_PRESERVATION.md').write_text(f'# Project preservation\n\nExact worker head `{a.source_sha}` contains frozen relayer base `{a.pr2_head}` so the same checkout runs standalone Across-Edge regressions plus worker gates. Worker code remains additive; PR #2 receives no worker commits and does not depend on ATM. Worker does not require a running relayer and has zero mutation/economic authority.\n\n`SHADOW_RELAYER_RESEARCH_CONTINUES=YES`  \n`PROJECT_CORE_CONTINUES=YES`  \n`READ_ONLY_AUTHORITY_PRESERVED=YES`\n')
 (E/'CI_EXACT_HEAD.md').write_text(f'# CI exact head\n\nGitHub Actions run `{a.run_id}` checks out and verifies exact SHA `{a.source_sha}`. The workflow runs full pytest/compile/project safety/secret gates, worker tests, fresh read-only RPC qualification, regenerates source-bound worker evidence, verifies its manifest, and uploads the evidence artifact.\n')
 runtime={'source_sha':a.source_sha,'pr2_head':a.pr2_head,'run_id':a.run_id,'outgoing_spend_usd':0,'financial_authority':0,'signing':0,'transaction_broadcast':0,'write_rpc':0};dump('CI_RUNTIME_IDENTITY.json',runtime)
 files=sorted(x for x in E.iterdir() if x.is_file() and x.name!='MANIFEST.sha256');(E/'MANIFEST.sha256').write_text(''.join(f'{sha(x)}  {x.name}\n' for x in files));print(f'WORKER_EVIDENCE_FINALIZED files={len(files)} source_sha={a.source_sha}')
if __name__=='__main__':raise SystemExit(main())
