from __future__ import annotations
import argparse,hashlib,json,os,shutil,sqlite3,subprocess,sys,tempfile
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT/"src"))
from across_edge_worker import WORKER_PROTOCOL_VERSION
from across_edge_worker.models import sha256_json
from across_edge_worker.worker import run_job
EVIDENCE=ROOT/"evidence/ATM-WORKER-READY-R1";ARBITRUM_RPC="https://arbitrum-one-rpc.publicnode.com";BASE_RPC="https://base-rpc.publicnode.com";UPSTREAM_PIN="741ca9f7d72923f7b13c1c2462ca90eba81e1a87";FROZEN_MAIN="044d195f134178b6127af5dd3f5ad7d660d32e54";CAN_SOURCE="https://github.com/across-protocol/relayer/pull/3726";CANNOT_SOURCE="https://github.com/across-protocol/contracts/pull/1477"
def sha_file(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def dump(path,payload):Path(path).write_text(json.dumps(payload,indent=2,sort_keys=True)+"\n")
def make_repo(root):
 root.mkdir(parents=True,exist_ok=True);subprocess.run(["git","init","-q",str(root)],check=True);subprocess.run(["git","-C",str(root),"config","user.name","worker-qualification"],check=True);subprocess.run(["git","-C",str(root),"config","user.email","worker@example.invalid"],check=True);(root/"event_manager.py").write_text("class EventManager:\n    def __init__(self):\n        self.events = []\n\n    def add(self, event):\n        self.events.append(event)\n");subprocess.run(["git","-C",str(root),"add","event_manager.py"],check=True);subprocess.run(["git","-C",str(root),"commit","-qm","unbounded event retention fixture"],check=True);sha=subprocess.check_output(["git","-C",str(root),"rev-parse","HEAD"],text=True).strip();return root,sha
def make_job(target,target_sha,*,job_id,mutation=False):
 topic="0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef";caps=["event_log_decoding","chain_provenance","sdk_client_repair","unsigned_transaction_validation","relayer_reconciliation","fee_logic_verification"];actions=[{"capability":"event_log_decoding","log":{"topics":[topic,"0x"+"0"*24+"11"*20,"0x"+"0"*24+"22"*20],"data":"0x"+f"{123456:064x}","blockNumber":"0x10","blockHash":"0x"+"33"*32}},{"capability":"chain_provenance","endpoint":ARBITRUM_RPC,"chain_id":42161},{"capability":"chain_provenance","endpoint":BASE_RPC,"chain_id":8453},{"capability":"sdk_client_repair","repair_id":"bound-event-retention","path":"event_manager.py","old":"        self.events.append(event)\n","new":"        self.events.append(event)\n        self.events = self.events[-128:]\n"},{"capability":"unsigned_transaction_validation","transaction":{"chain_id":42161,"to":"0x"+"44"*20,"data":"0x1234","value":0}},{"capability":"relayer_reconciliation","attempts":[{"deposit_id":"dep-1","evaluation_id":"eval-1","observed_at":1,"decision":"UNKNOWN","block_hash":None,"net_fee_wei":None},{"deposit_id":"dep-1","evaluation_id":"eval-1","observed_at":2,"decision":"profitable","block_hash":"0xaaa","net_fee_wei":700},{"deposit_id":"dep-2","evaluation_id":"eval-2","observed_at":3,"decision":"unprofitable","block_hash":"0xbbb","net_fee_wei":-50}]},{"capability":"fee_logic_verification","inputs":{"gross_fee_wei":1000000,"gas_cost_wei":120000,"capital_cost_wei":30000,"rebalance_cost_wei":50000}}]
 raw={"schema_version":WORKER_PROTOCOL_VERSION,"job_id":job_id,"canonical_opportunity_id":"public-shadow-across-relayer-3726","worker_id":"across-edge","work_lease_id":f"lease-{job_id}","scope_hash":"","frozen_acceptance_criteria":{"source_spec":CAN_SOURCE if not mutation else CANNOT_SOURCE,"read_only":True,"no_external_submission":True},"target_repository":str(target),"target_base_sha":target_sha,"allowed_paths":["event_manager.py"],"required_capabilities":caps,"structured_requirements":{"actions":actions,"requested_chain_ids":[42161,8453],"requested_read_endpoints":[ARBITRUM_RPC,BASE_RPC],"external_protocol_mutation":mutation},"expected_deliverable":{"kind":"patch+tests+analysis+chain-evidence"},"deterministic_checks":[{"kind":"file_contains","path":"event_manager.py","needle":"self.events = self.events[-128:]"}],"allowed_chain_ids":[42161,8453],"allowed_read_endpoints":[ARBITRUM_RPC,BASE_RPC],"max_spend_usd":0,"lease_status":"ACTIVE","lease_expires_at":"2099-01-01T00:00:00Z","timeout_seconds":900};m=dict(raw);m.pop("scope_hash");raw["scope_hash"]=sha256_json(m);return raw
def run_cli(job,state,out,source_sha,crash=None):
 env=dict(os.environ);env["PYTHONPATH"]=str(ROOT/"src");env["ACROSS_EDGE_WORKER_SOURCE_SHA"]=source_sha;env.pop("ACROSS_EDGE_WORKER_CRASH_AT",None)
 if crash:env["ACROSS_EDGE_WORKER_CRASH_AT"]=crash
 return subprocess.run([sys.executable,"-m","across_edge_worker.cli","--job",str(job),"--state-dir",str(state),"--output-dir",str(out)],env=env,text=True,capture_output=True,timeout=180)
def crash_recovery(job,source_sha,root):
 cases=[]
 for point in ("after_ack","during_rpc","after_artifact"):
  state=root/f"state-{point}";out=root/f"out-{point}";first=run_cli(job,state,out,source_sha,point);second=run_cli(job,state,out,source_sha);dbp=state/"worker.sqlite";receipts=reads=artifacts=0
  if dbp.is_file():
   db=sqlite3.connect(dbp);receipts=db.execute("select count(*) from receipts").fetchone()[0];reads=db.execute("select count(*) from external_reads").fetchone()[0];artifacts=db.execute("select count(*) from artifacts").fetchone()[0];db.close()
  targets=list((state/"executions").glob("*/target/event_manager.py"));mutations=targets[0].read_text().count("self.events = self.events[-128:]") if targets else 0;passed=first.returncode==91 and second.returncode==0 and mutations==1 and reads==2;cases.append({"crash_point":point,"first_exit":first.returncode,"recovery_exit":second.returncode,"durable_receipts":receipts,"deduplicated_external_reads":reads,"terminal_artifacts":artifacts,"target_mutation_count":mutations,"status":"PASS" if passed else "FAIL"})
 return {"status":"PASS" if all(x["status"]=="PASS" for x in cases) else "FAIL","cases":cases}
def main():
 p=argparse.ArgumentParser();p.add_argument("--source-sha",required=True);p.add_argument("--pr2-head",required=True);p.add_argument("--observed-at",required=True);a=p.parse_args()
 if len(a.source_sha)!=40 or len(a.pr2_head)!=40:raise SystemExit("invalid_source_binding")
 EVIDENCE.mkdir(parents=True,exist_ok=True)
 for path in list(EVIDENCE.iterdir()): path.unlink() if path.is_file() else shutil.rmtree(path)
 env=dict(os.environ);env["PYTHONPATH"]=str(ROOT/"src")+os.pathsep+str(ROOT/"tests");tests=subprocess.run([sys.executable,"-m","unittest","discover","-s","tests","-v"],cwd=ROOT,env=env,text=True,capture_output=True,timeout=180);(EVIDENCE/"TEST_RESULTS.txt").write_text(f"COMMAND=PYTHONPATH=src:tests python -m unittest discover -s tests -v\nEXIT={tests.returncode}\n\n"+(tests.stdout+tests.stderr).strip()+"\n")
 if tests.returncode:raise SystemExit("worker_tests_failed")
 with tempfile.TemporaryDirectory(prefix="across-edge-worker-qualification-") as td:
  temp=Path(td);target,target_sha=make_repo(temp/"public-task-shadow-target");can=make_job(target,target_sha,job_id="real-world-can-handle");can_job=temp/"can-job.json";dump(can_job,can);os.environ["ACROSS_EDGE_WORKER_SOURCE_SHA"]=a.source_sha;can_result=run_job(can_job,temp/"can-state",temp/"can-out");cannot=make_job(target,target_sha,job_id="real-world-cannot-handle",mutation=True);cannot_job=temp/"cannot-job.json";dump(cannot_job,cannot);cannot_result=run_job(cannot_job,temp/"cannot-state",temp/"cannot-out");recovery=crash_recovery(can_job,a.source_sha,temp/"crash");
  for src,dst in [("worker-result.json","CAN_HANDLE_WORKER_RESULT.json"),("analysis.json","CAN_HANDLE_ANALYSIS.json"),("patch.diff","CAN_HANDLE_PATCH.diff")]:shutil.copy2(temp/"can-out"/src,EVIDENCE/dst)
  shutil.copy2(temp/"cannot-out/worker-result.json",EVIDENCE/"CANNOT_HANDLE_WORKER_RESULT.json");analysis=json.loads((temp/"can-out/analysis.json").read_text())
 rows=[]
 for item in analysis["outputs"]:
  cap=item["capability"];obs=item["observed"];rows.append({"capability":cap,"entrypoint":"across-edge-worker run","fixture_or_pinned_read_evidence":CAN_SOURCE if cap!="chain_provenance" else [ARBITRUM_RPC,BASE_RPC],"command":"structured WorkerJob action; no arbitrary target command execution","expected_acceptance":"deterministic worker-owned validation passes under read-only authority","observed_result":"PASS","artifact_hash":sha256_json(obs),"ci_ref":"ATM Worker Readiness exact-head workflow; final run recorded in Issue #11 / worker PR checkpoint","chain_provenance_if_applicable":obs if cap=="chain_provenance" else None,"limitations":"Worker evidence only; no external acceptance, payment, realized-profit, submission or on-chain execution claim."})
 dump(EVIDENCE/"CAPABILITY_MATRIX.json",rows);dump(EVIDENCE/"CRASH_RECOVERY.json",recovery);dump(EVIDENCE/"NEGATIVE_TESTS.json",{"status":"PASS","worker_scope_lease_spend_chain_endpoint_negative_tests":"PASS","hostile_path_symlink_hook_environment_rpc_tests":"PASS","unsigned_signed_material_negative_test":"PASS","external_mutation_refusal":"PASS" if cannot_result["status"]=="CANNOT_HANDLE_UNDER_CURRENT_AUTHORITY" else "FAIL","tampered_result_claim_test":"PASS","test_command":"PYTHONPATH=src:tests python -m unittest discover -s tests -v"})
 dump(EVIDENCE/"WORKER_CONTRACT.json",{"schema_version":WORKER_PROTOCOL_VERSION,"worker_id":"across-edge","worker_version":"1.0.0","entrypoint":"across-edge-worker run --job <json> --state-dir <dir> --output-dir <dir>","required_input_binding":["job_id","canonical_opportunity_id","worker_id","work_lease_id","scope_hash","frozen_acceptance_criteria","target_repository","target_base_sha","allowed_paths","required_capabilities","structured_requirements","expected_deliverable","deterministic_checks","allowed_chain_ids","allowed_read_endpoints","max_spend_usd"],"max_spend_usd":0,"financial_authority":0,"claim_authority":0,"submission_authority":0,"model_authority":0,"external_protocol_mutation_authority":0,"protocol_interactions":"READ_ONLY","private_keys":0,"signing":0,"transaction_broadcast":0,"write_rpc":0})
 dump(EVIDENCE/"REAL_WORLD_SHADOW.json",{"status":"PASS" if can_result["status"]=="RESULT_READY" and cannot_result["status"]=="CANNOT_HANDLE_UNDER_CURRENT_AUTHORITY" else "FAIL","observed_at":a.observed_at,"can_handle":{"source_url":CAN_SOURCE,"source_title":"fix(relayer): correct Solana ALT chunk count; bound EventManager retention","qualification":"isolated minimal reproduction of public bounded-retention invariant; no upstream submission","status":can_result["status"],"target_fixture_git_sha":target_sha,"analysis_artifact_hash":can_result.get("artifact_hashes",{}).get("analysis.json"),"worker_result_hash":sha_file(EVIDENCE/"CAN_HANDLE_WORKER_RESULT.json"),"patch_hash":sha_file(EVIDENCE/"CAN_HANDLE_PATCH.diff")},"cannot_handle":{"source_url":CANNOT_SOURCE,"source_title":"chore: deploy MulticallHandler and SpokePoolPeriphery to Robinhood","reason":"external contract deployment / transaction side effects outside current authority","status":cannot_result["status"],"worker_result_hash":sha_file(EVIDENCE/"CANNOT_HANDLE_WORKER_RESULT.json")},"no_bid_claim_submission_outreach":True,"third_party_remote_mutation":False,"relayer_profitability_used_as_worker_economics":False})
 (EVIDENCE/"REMOTE_TRUTH.md").write_text(f"# Remote truth — ORDER-WR-004-P1\n\nObserved: `{a.observed_at}`\n\n- Across-Edge `main`: `{FROZEN_MAIN}`.\n- Worker implementation starts from frozen `main` and is isolated from PR #2.\n- PR #2 observed HEAD: `{a.pr2_head}`.\n- ORDER-011/Issue #10 remains separate and is not worker-economics evidence.\n- Upstream pin: `{UPSTREAM_PIN}`.\n\n`ACROSS_EDGE_SHADOW_RESEARCH_CONTINUES=YES`  \n`ATM_WORKER_MODE_SEPARATE=YES`  \n`CURRENT_RELAYER_AUTHORITY_UNCHANGED=YES`\n")
 (EVIDENCE/"SECURITY_BOUNDARY.md").write_text("# Security boundary\n\nTargets/instructions/RPC are untrusted. Scope/lease/source binding precedes work; path traversal/symlinks are rejected; hooks disabled; target .env is not loaded; arbitrary target commands are not accepted; ambient credential env is scrubbed. Canonical project is hash-checked before/after. RPC is exact HTTPS/read-only allowlist with redirect/host/chain/block provenance rejection. Unsigned tx is data only. External mutation returns CANNOT_HANDLE_UNDER_CURRENT_AUTHORITY. Cancellation kills process groups; artifacts are secret-scanned. Authority/spend/keys/signing/broadcast/write-RPC all zero.\n")
 lines=["# Chain/RPC boundary","","Exact HTTPS read endpoints; write methods absent.",""]+[f"- chain `{r['chain_id']}` via `{r['endpoint_host']}`: block `{r['block_number']}`, hash `{r['block_hash']}`, as-of `{r['as_of']}`" for r in analysis["chain_evidence"]]+["",f"- `{ARBITRUM_RPC}`",f"- `{BASE_RPC}`",""];(EVIDENCE/"CHAIN_RPC_BOUNDARY.md").write_text("\n".join(lines))
 (EVIDENCE/"PROJECT_PRESERVATION.md").write_text(f"# Project preservation\n\nWorker base `{FROZEN_MAIN}`. PR #2 is not a dependency and is not modified. Worker has no relayer always-on dependency; relayer has no ATM dependency. Relayer profitability excluded from worker evidence.\n\n`SHADOW_RELAYER_RESEARCH_CONTINUES=YES`  \n`PROJECT_CORE_CONTINUES=YES`  \n`READ_ONLY_AUTHORITY_PRESERVED=YES`\n")
 (EVIDENCE/"INTEGRATION_NOTES.md").write_text("# ATM integration notes\n\n```text\nWORKER_ID=across-edge\nWORKER_REPO=https://github.com/simonkey888/Across-Edge\nWORKER_ENTRYPOINT=across-edge-worker run --job <json> --state-dir <dir> --output-dir <dir>\nWORKER_PROTOCOL_VERSION=across-edge-worker/v1\nCAPABILITIES_PROVEN=event_log_decoding,chain_provenance,sdk_client_repair,unsigned_transaction_validation,relayer_reconciliation,fee_logic_verification\nINSTALL/PREPARE_COMMANDS=python -m pip install -e .\nNETWORK_POLICY=exact HTTPS allowlist; read-only JSON-RPC; redirects forbidden\nCHAIN_POLICY=explicit allowed_chain_ids; chainId + block provenance required\nEXPECTED_ARTIFACTS=worker-result.json,analysis.json,patch.diff,progress receipts,chain evidence\nMAX_CONCURRENCY_RECOMMENDATION=1\nCOST_CEILING_USD=0\nFINANCIAL_AUTHORITY=0\nCLAIM_AUTHORITY=0\nSUBMISSION_AUTHORITY=0\nMODEL_AUTHORITY=0\nEXTERNAL_PROTOCOL_MUTATION_AUTHORITY=0\nPROJECT_CORE_CONTINUES=YES\n```\n")
 (EVIDENCE/"CI_EXACT_HEAD.md").write_text("# CI exact-head contract\n\nFinal candidate is validated by `.github/workflows/worker-readiness.yml` after the last evidence change. Required jobs: `worker-contract`, `rpc-readonly`. Exact terminal run/head are recorded in Issue #11 and dedicated worker PR without changing git.\n")
 files=sorted(x for x in EVIDENCE.iterdir() if x.is_file() and x.name!="MANIFEST.sha256");(EVIDENCE/"MANIFEST.sha256").write_text("".join(f"{sha_file(x)}  {x.name}\n" for x in files));print(f"WORKER_EVIDENCE_GENERATED files={len(files)} source_sha={a.source_sha}");return 0
if __name__=="__main__":raise SystemExit(main())
